-- Migration 002: Consent records & per-session health screening
CREATE TABLE IF NOT EXISTS consent_records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  appointment_id INT NULL,
  customer_id INT NOT NULL,
  date_of_birth DATE NULL,
  calculated_age INT NULL,
  id_type VARCHAR(100) NULL,
  id_last_four VARCHAR(10) NULL,
  id_verified_by INT NULL,
  id_verified_at DATETIME NULL,
  guardian_name VARCHAR(255) NULL,
  guardian_relationship VARCHAR(100) NULL,
  guardian_id_number VARCHAR(100) NULL,
  guardian_signature TEXT NULL,
  guardian_present TINYINT(1) DEFAULT 0,
  medical_conditions_acknowledged TINYINT(1) DEFAULT 1,
  aftercare_acknowledged TINYINT(1) DEFAULT 1,
  risks_acknowledged TINYINT(1) DEFAULT 1,
  signature_data TEXT NULL,
  witness_name VARCHAR(255) NULL,
  accepted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50) DEFAULT 'active',
  withdrawn_at DATETIME NULL,
  withdrawal_reason TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS session_health_screenings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  appointment_id INT NOT NULL,
  customer_id INT NOT NULL,
  allergies TEXT NULL,
  medications_blood_thinners TEXT NULL,
  has_diabetes TINYINT(1) DEFAULT 0,
  has_skin_disorders TINYINT(1) DEFAULT 0,
  is_pregnant_nursing TINYINT(1) DEFAULT 0,
  has_bleeding_conditions TINYINT(1) DEFAULT 0,
  has_immune_conditions TINYINT(1) DEFAULT 0,
  recent_illness_infection TINYINT(1) DEFAULT 0,
  alcohol_drug_influence TINYINT(1) DEFAULT 0,
  site_skin_condition VARCHAR(255) NULL,
  reviewed_by_artist_id INT NULL,
  reviewed_at DATETIME NULL,
  clearance_status VARCHAR(50) DEFAULT 'pending',
  refusal_reason TEXT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
